
---
- name: restart apache
  service:
    name: apache2
    state: restarted
  become: yes

- name: reload apache
  service:
    name: apache2
    state: reloaded
  become: yes

- name: restart logrotate
  service:
    name: logrotate
    state: reloaded
  become: yes  