---
- hosts: servers
  gather_facts: yes
  become: yes

  tasks:
    - block:
      - debug:
          msg: 'This server is running Ubuntu 20.04 LTS and will be upgraded to 22.04 LTS.'

      - name: Perform a dist-upgrade.
        ansible.builtin.apt:
          upgrade: dist
          update_cache: yes

      - name: Check if a reboot is required.
        ansible.builtin.stat:
          path: /var/run/reboot-required
          get_md5: no
        register: reboot_required_file

      - name: Reboot the server (if required).
        ansible.builtin.reboot:
        when: reboot_required_file.stat.exists == true

      - name: Remove dependencies that are no longer required.
        ansible.builtin.apt:
          autoremove: yes

      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_version == '20.04'
