
---
- name: restart fpm
  service:
    name: php{{ php_version }}-fpm
    state: restarted
  become: yes

- name: reload fpm
  service:
    name: php{{ php_version }}-fpm
    state: reloaded
  become: yes